spring.datasource.url=jdbc:mysql://localhost:3306/chatdb
spring.datasource.username=root
spring.datasource.password=vaibhav

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaibhavbk2124@gmail.com
spring.mail.password=vpeabqxcwabfppnc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

server.port=8082